export const CREATE_APPOINTMENT_REQUEST = "CREATE_APPOINTMENT_REQUEST"
export const CREATE_APPOINTMENT_SUCCESS = "CREATE_APPOINTMENT_SUCCESS"
export const CREATE_APPOINTMENT_FAIL = "CREATE_APPOINTMENT_FAIL"

export const MY_APPOINTMENTS_REQUEST = "MY_APPOINTMENTS_REQUEST"
export const MY_APPOINTMENTS_SUCCESS = "MY_APPOINTMENTS_SUCCESS"
export const MY_APPOINTMENTS_FAIL = "MY_APPOINTMENTS_FAIL"

export const ALL_APPOINTMENTS_REQUEST = "ALL_APPOINTMENTS_REQUEST"
export const ALL_APPOINTMENTS_SUCCESS = "ALL_APPOINTMENTS_SUCCESS"
export const ALL_APPOINTMENTS_FAIL = "ALL_APPOINTMENTS_FAIL"

export const APPOINTMENT_DETAILS_REQUEST = "APPOINTMENT_DETAILS_REQUEST";
export const APPOINTMENT_DETAILS_SUCCESS = "APPOINTMENT_DETAILS_SUCCESS";
export const APPOINTMENT_DETAILS_FAIL = "APPOINTMENT_DETAILS_FAIL";

export const ALL_DOCTORS_REQUEST = "ALL_DOCTORS_REQUEST";
export const ALL_DOCTORS_SUCCESS = "ALL_DOCTORS_SUCCESS";
export const ALL_DOCTORS_FAIL = "ALL_DOCTORS_FAIL";

export const UPDATE_APPOINTMENT_STATUS_REQUEST = "UPDATE_APPOINTMENT_STATUS_REQUEST";
export const UPDATE_APPOINTMENT_STATUS_SUCCESS = "UPDATE_APPOINTMENT_STATUS_SUCCESS";
export const UPDATE_APPOINTMENT_STATUS_FAIL = "UPDATE_APPOINTMENT_STATUS_FAIL";
export const UPDATE_APPOINTMENT_STATUS_RESET = "UPDATE_APPOINTMENT_STATUS_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS"