export const PHARMACY_REGISTER_REQUEST = 'PHARMACY_REGISTER_REQUEST';
export const PHARMACY_REGISTER_SUCCESS = 'PHARMACY_REGISTER_SUCCESS';
export const PHARMACY_REGISTER_FAIL = 'PHARMACY_REGISTER_FAIL';

export const PHARMACY_DETAILS_REQUEST = 'PHARMACY_DETAILS_REQUEST';
export const PHARMACY_DETAILS_SUCCESS = 'PHARMACY_DETAILS_SUCCESS';
export const PHARMACY_DETAILS_FAIL = 'PHARMACY_DETAILS_FAIL';

export const MY_PHARMACY_REQUEST = 'MY_PHARMACY_REQUEST';
export const MY_PHARMACY_SUCCESS = 'MY_PHARMACY_SUCCESS';
export const MY_PHARMACY_FAIL = 'MY_PHARMACY_FAIL';

export const PHARMACY_UPDATE_REQUEST = 'PHARMACY_UPDATE_REQUEST';
export const PHARMACY_UPDATE_SUCCESS = 'PHARMACY_UPDATE_SUCCESS';
export const PHARMACY_UPDATE_FAIL = 'PHARMACY_UPDATE_FAIL';

export const PHARMACY_STATS_REQUEST = 'PHARMACY_STATS_REQUEST';
export const PHARMACY_STATS_SUCCESS = 'PHARMACY_STATS_SUCCESS';
export const PHARMACY_STATS_FAIL = 'PHARMACY_STATS_FAIL';

export const PHARMACY_MEDICINES_REQUEST = 'PHARMACY_MEDICINES_REQUEST';
export const PHARMACY_MEDICINES_SUCCESS = 'PHARMACY_MEDICINES_SUCCESS';
export const PHARMACY_MEDICINES_FAIL = 'PHARMACY_MEDICINES_FAIL';

export const ADD_MEDICINE_REQUEST = 'ADD_MEDICINE_REQUEST';
export const ADD_MEDICINE_SUCCESS = 'ADD_MEDICINE_SUCCESS';
export const ADD_MEDICINE_FAIL = 'ADD_MEDICINE_FAIL';

export const UPDATE_MEDICINE_REQUEST = 'UPDATE_MEDICINE_REQUEST';
export const UPDATE_MEDICINE_SUCCESS = 'UPDATE_MEDICINE_SUCCESS';
export const UPDATE_MEDICINE_FAIL = 'UPDATE_MEDICINE_FAIL';

export const DELETE_MEDICINE_REQUEST = 'DELETE_MEDICINE_REQUEST';
export const DELETE_MEDICINE_SUCCESS = 'DELETE_MEDICINE_SUCCESS';
export const DELETE_MEDICINE_FAIL = 'DELETE_MEDICINE_FAIL';

export const BULK_UPLOAD_MEDICINES_REQUEST = 'BULK_UPLOAD_MEDICINES_REQUEST';
export const BULK_UPLOAD_MEDICINES_SUCCESS = 'BULK_UPLOAD_MEDICINES_SUCCESS';
export const BULK_UPLOAD_MEDICINES_FAIL = 'BULK_UPLOAD_MEDICINES_FAIL';

export const LOW_STOCK_MEDICINES_REQUEST = 'LOW_STOCK_MEDICINES_REQUEST';
export const LOW_STOCK_MEDICINES_SUCCESS = 'LOW_STOCK_MEDICINES_SUCCESS';
export const LOW_STOCK_MEDICINES_FAIL = 'LOW_STOCK_MEDICINES_FAIL';

export const EXPIRING_MEDICINES_REQUEST = 'EXPIRING_MEDICINES_REQUEST';
export const EXPIRING_MEDICINES_SUCCESS = 'EXPIRING_MEDICINES_SUCCESS';
export const EXPIRING_MEDICINES_FAIL = 'EXPIRING_MEDICINES_FAIL';

export const PHARMACY_ORDERS_REQUEST = 'PHARMACY_ORDERS_REQUEST';
export const PHARMACY_ORDERS_SUCCESS = 'PHARMACY_ORDERS_SUCCESS';
export const PHARMACY_ORDERS_FAIL = 'PHARMACY_ORDERS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
