export const CREATE_PRESCRIPTION_REQUEST = "CREATE_PRESCRIPTION_REQUEST";
export const CREATE_PRESCRIPTION_SUCCESS = "CREATE_PRESCRIPTION_SUCCESS";
export const CREATE_PRESCRIPTION_FAIL = "CREATE_PRESCRIPTION_FAIL";

export const GET_PRESCRIPTIONS_REQUEST = "GET_PRESCRIPTIONS_REQUEST";
export const GET_PRESCRIPTIONS_SUCCESS = "GET_PRESCRIPTIONS_SUCCESS";
export const GET_PRESCRIPTIONS_FAIL = "GET_PRESCRIPTIONS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";